### ISSUE TITLE
Default src image

### ISSUE THREAD

**Issue by tplessis** [kevindew/jekyll-srcset-tag#1]
Default "src" image is always the latest. Btw, this is always the smallest. For browsers that does not support srcset yet, default image will be too small.

And if i try to set the biggest image as the last element in the "srcset" array, every images are blur because it use the previous image to resize the next. :/

It would be great if we could choose the image to set as the default "src".

Regards,
Thomas

**Comment by kevindew** [comment]
Hey there, I've just added in the ability to do this with the 0.2.0 version. You can specify `fallback:true` on any of your `{% srcset_source %}` images to specify which one is output in the `<img src />`.

**Comment by tplessis** [comment]
Works great! Thx Kevin! :+1:
